In [1]:
#import
import cv2
import numpy as np
import glob
import copy
import os


video_name = 'APR08_2018_C_DJI_0010'
positions_path = '/media/golden/72FFC6EE48B5CF39/drone_tracking/kenya-tracking/processed_videos/' + video_name + '/localizations/positions.npy'      #the dots marking the animals on each frame
tracks_path = '/media/golden/72FFC6EE48B5CF39/drone_tracking/kenya-tracking/processed_videos/' + video_name + '/localizations/tracks-complete.npy'            #file containing info about the tracks
picture_folder_path = '/media/golden/72FFC6EE48B5CF39/drone-tracking/kenya-tracking/raw_frames/scare_clips/*/' + video_name + '/*jpg'   #folder with the pictures
boxes_path = '/media/golden/72FFC6EE48B5CF39/drone_tracking/kenya-tracking/processed_videos/' + video_name + '/localizations/boxes.npy' 
extracts_path = '/media/golden/72FFC6EE48B5CF39/drone_tracking/kenya-tracking/processed_videos/' + video_name + '/extracts/'
save_path = '/media/golden/72FFC6EE48B5CF39/drone_tracking/kenya-tracking/processed_videos/' + video_name + '/track_images/'
if not os.path.isdir(save_path):
    os.mkdir(save_path)
factor = 0.9                                                   #how much you want to shrink the original image
skip = 1                                                         #how many frames you want to skip
show_all_tracks = True



NameError: name 'os' is not defined

In [56]:
tracks = np.load(tracks_path)
extracts = glob.glob(extracts_path + '/*')
extracts.sort(key=lambda file: int(file.split('_')[-1]))

In [74]:

extracts = glob.glob(extracts_path + '*/*/*.png')
extracts.sort(key=lambda file: int(file.split('.')[-5].split('_')[-1]))

In [57]:
extracts_file = []
for frame in range(len(extracts)):
    extracts_file.append(glob.glob(extracts[frame] + '/*/*'))
    extracts_file[-1].sort(key=lambda file: int(file.split('.')[-3]))

In [69]:
import shutil 

track_ind = 5
for track_ind in range(len(tracks)):
    track = tracks[track_ind]
    track_folder = os.path.join(save_path, 'track_' + str(track_ind))
    if os.path.isdir(track_folder):
        continue
    else:
        os.mkdir(track_folder)
        for step in range(len(track['pos_index'])):
        # for step in range(10):
            pos_index = track['pos_index'][step - track['first_frame']][0]
            if not np.isnan(pos_index): 
                image_file = extracts_file[step][int(pos_index)]
                shutil.copyfile(image_file, os.path.join(track_folder, os.path.basename(image_file)))

In [ ]:
len(window.listoftracks)

In [5]:
import numpy as np
import matplotlib.pyplot as plt
import copy
tracks_path = '/media/golden/72FFC6EE48B5CF39/kenya-tracking/processed_videos/APR03_2018_C_DJI_0284/localizations/tracks.npy' 

In [6]:
tracks = np.load(tracks_path)

In [9]:
starting_frame = [track['first_frame'] for track in tracks]


In [8]:
import numpy as np
x = np.ones((10,2))
y = np.ones((10,2)) * 10

In [2]:
x = 10

In [3]:
if x == 10:
    x = 5
else:
    print('here')

In [11]:
z

array([[ 5.5,  5.5]])

In [1]:
x = [{'c': 10, 'k': 1}, {'c': 3, 'k': 2}, {'c': 5, 'k': 3}]

In [2]:
import copy

In [3]:
x_copy = copy.copy(x)

In [4]:
print(x)
print(x_copy)

[{'k': 1, 'c': 10}, {'k': 2, 'c': 3}, {'k': 3, 'c': 5}]
[{'k': 1, 'c': 10}, {'k': 2, 'c': 3}, {'k': 3, 'c': 5}]


In [5]:
def sort(item):
    return item['c']

In [6]:
x_copy.sort(key=sort)

In [7]:
print(x)
print(x_copy)

[{'k': 1, 'c': 10}, {'k': 2, 'c': 3}, {'k': 3, 'c': 5}]
[{'k': 2, 'c': 3}, {'k': 3, 'c': 5}, {'k': 1, 'c': 10}]


In [8]:
x_copy[0]['c'] = -2

In [9]:
x_copy.append({'c':-13, 'k':-2})

In [10]:
print(x)
print(x_copy)

[{'k': 1, 'c': 10}, {'k': 2, 'c': -2}, {'k': 3, 'c': 5}]
[{'k': 2, 'c': -2}, {'k': 3, 'c': 5}, {'k': 1, 'c': 10}, {'k': -2, 'c': -13}]


In [11]:
x[0]['new'] = 1000

In [18]:
print(x)
print(x_copy)

[{'k': array([ 1.,  1.]), 'c': 5}]
[{'k': 2, 'c': -2}, {'k': array([ 1.,  1.]), 'c': 5}, {'k': 1, 'new': 1000, 'c': 10}, {'k': -2, 'c': -13}]


In [13]:
del x[0]

In [14]:
print(len(x))
print(len(x_copy))

2
4


In [2]:
import numpy as np
x = np.load('/media/golden/72FFC6EE48B5CF39/drone-tracking/kenya-tracking/processed_videos/APR03_2018_C_DJI_0284/localizations/positions.npy' )

In [12]:
print(x[0].shape)
print(np.ones((1,2)).shape)
print(np.vstack([x[0], np.ones((1,2))]))

(12, 2)
(1, 2)
[[  8.05952515e+02   8.69874329e+02]
 [  7.42794312e+02   2.36526294e+03]
 [  9.41179443e+02   1.02659216e+03]
 [  9.67757202e+02   9.42120605e+02]
 [  9.32276245e+02   2.21676831e+03]
 [  7.97129028e+02   2.25654980e+03]
 [  1.04837268e+03   1.73531519e+03]
 [  8.93669312e+02   9.65061218e+02]
 [  9.70521851e+02   1.05232141e+03]
 [  6.90568604e+02   1.82026025e+03]
 [  8.29639893e+02   1.71730188e+03]
 [  7.89107910e+02   2.17300659e+03]
 [  1.00000000e+00   1.00000000e+00]]


In [4]:
x = np.ones(10)

In [5]:
len(x[:-1])

9

In [16]:
y = np.load('test.npy')

In [7]:
np.arange(10)[-1:]

array([9])